version: '3'
services:
  postgres:
    container_name: postgres
    image: 'postgres'
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root

  app:
    container_name: app
    build: ./backend/

  web:
    container_name: web
    build: ./frontend
    ports:
      - '80:80'
